version: 0.1.{build}
branches:
  only:
  - master
build_script:
- cmd: C:\projects\scm-backup\build-release.bat
test: off
artifacts:
- path: release\scm-backup-*.zip
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'