version: 0.1.{build}
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
- cmd: C:\projects\scm-backup\build-release.bat
test: off
artifacts:
- path: release\scm-backup-*.zip
  name: Release Version
- path: src\ScmBackup.Tests.Integration\bin\Release\netcoreapp2.0\*.log
  name: Integration Test Logfile
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'